cargo-features = ["strip"]

[package]
name = "libosu-test"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[dependencies]
anyhow = "1.0.0"
indicatif = "0.17.0-beta.1"
libosu = { git = "https://github.com/LavaDesu/libosu", branch = "staging/all2" }
rayon = "1.5.1"
